export const ADD_EMPLOYEE = 'REPORT_ADD_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REPORT_REMOVE_EMPLOYEE';
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SHOW_LOADER = 'SHOW_LOADER';
export const REPORT = {
    ADD_EMPLOYEE : 'ADD_EMPLOYEE',
    REMOVE_EMPLOYEE : 'REMOVE_EMPLOYEE',
    EDIT_EMPLOYEE : 'EDIT_EMPLOYEE ',
    GET_REPORT : 'ADD_REPORT'
};